version: '3.9'

services:
  backswtesis:
    build: .  
    restart: always  
    container_name: backswtesis  
    command: python manage.py runserver 0.0.0.0:8000  
    volumes:
      - .:/code_free  
    ports:
      - "8080:8000"  
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings  
      - DEBUG=True  
      - SECRET_KEY=django-insecure---&r5uu^d_j%@t%*(srr^jn4vl$ug_m6!ncba&09z#@sg*!h*k  
      - ALLOWED_HOSTS=*
      - SUPABASE_DB_NAME=postgres 
      - SUPABASE_DB_USER=postgres.enmwboxeagizifyvnxys 
      - SUPABASE_DB_PASSWORD=Pelachito1@ 
      - SUPABASE_DB_HOST=aws-0-ca-central-1.pooler.supabase.com
      - SUPABASE_DB_PORT=5432  

