# Generated by Django 4.0.3 on 2025-02-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=255, null=True)),
                ('nro_celular', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodocumento')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesis', models.CharField(blank=True, max_length=255, null=True)),
                ('universidad', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_plataforma', models.CharField(blank=True, max_length=25, null=True)),
                ('clave_plataforma', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registros.clientes')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'db_table': 'tesis',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesis', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_cuotas', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_cuotas', models.CharField(blank=True, max_length=100, null=True)),
                ('cuotas_cancelado', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_cancelado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registros.clientes')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('formapago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formapago')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
    ]
