# Generated by Django 4.0.3 on 2025-03-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesis',
            old_name='tesis',
            new_name='nombre_tesis',
        ),
    ]
